package com.migrator.core.impl.oracle;

import com.migrator.core.DbVersionRepository;
import com.migrator.model.MigrationScript;

import java.sql.*;
import java.util.HashSet;
import java.util.Set;

public class OracleDbVersionRepository implements DbVersionRepository {
    private final Connection connection;

    public OracleDbVersionRepository(Connection connection) {
        this.connection = connection;
    }

    @Override
    public Set<String> getAppliedVersions() {
        Set<String> versions = new HashSet<>();

        try {
            ensureSchemaMigrationsTable();

            try (PreparedStatement stmt = connection.prepareStatement(
                    "SELECT version FROM schema_migrations"
            )) {
                ResultSet rs = stmt.executeQuery();
                while (rs.next()) {
                    versions.add(rs.getString("version"));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Failed to fetch applied migrations", e);
        }

        return versions;
    }

    @Override
    public void save(MigrationScript script) {
        try (PreparedStatement stmt = connection.prepareStatement(
                """
                INSERT INTO schema_migrations
                    (version, description, checksum)
                VALUES (?, ?, ?)
                """
        )) {
            stmt.setString(1, script.getVersion());
            stmt.setString(2, script.getDescription());
            stmt.setString(3, script.getChecksum());
            stmt.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException(
                    "Failed to save migration record for version " + script.getVersion(), e
            );
        }
    }

    /**
     * Creates schema_migrations table if it does not exist (Oracle compatible).
     */
    private void ensureSchemaMigrationsTable() throws SQLException {

        // Check table existence via USER_TABLES
        String checkSql = """
            SELECT COUNT(*) FROM user_tables
            WHERE table_name = 'SCHEMA_MIGRATIONS'
        """;

        try (Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(checkSql)) {

            rs.next();
            if (rs.getInt(1) > 0) {
                return;
            }
        }

        // Create table
        String createSql = """
            CREATE TABLE schema_migrations (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                version VARCHAR2(50) NOT NULL UNIQUE,
                description VARCHAR2(255),
                applied_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                checksum VARCHAR2(255)
            )
        """;

        try (Statement stmt = connection.createStatement()) {
            stmt.execute(createSql);
        }
    }
}
